apiVersion: v1
entries:
  cronjob:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-05-05T14:17:18.63549-05:00"
    description: A Helm chart for deploying a CronJob.
    digest: 6aae2e1d2e1a3a0258cbf7d6ab862a8008dc5bc57539181a9ef68487b6417e1e
    name: cronjob
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/cronjob-v0.1.0.tgz
    version: v0.1.0
  httpd:
  - apiVersion: v2
    appVersion: 2.4.54
    created: "2026-05-05T14:17:18.636557-05:00"
    description: A Helm chart to deploy httpd in Kubernetes
    digest: 3af2b85c70ceb4e13d0d260456894eca93aa7aaeaabd905b40a69e6faada27cc
    name: httpd
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/httpd-v0.1.1.tgz
    version: v0.1.1
generated: "2026-05-05T14:17:18.634706-05:00"
