apiVersion: v1
entries:
  cronjob:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-05-05T19:05:08.398175-05:00"
    description: A Helm chart for deploying a CronJob.
    digest: 4a4838cc0c814ca253a54c62ef6d848da94bc9a3594b938a83f7b03ca6f6eb38
    name: cronjob
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/cronjob-v0.1.0.tgz
    version: v0.1.0
  httpd:
  - apiVersion: v2
    appVersion: 2.4.54
    created: "2026-05-05T19:05:08.399369-05:00"
    description: A Helm chart to deploy httpd in Kubernetes
    digest: 984f8483f38f67bfa8a1c4c964ebe6059195d9d12124530963a89db85a9d6616
    name: httpd
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/httpd-v0.1.1.tgz
    version: v0.1.1
  yourls:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Add diggest parameters to prepare bitnami/common v2
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Upstream Project
          url: https://github.com/YOURLS/YOURLS
      artifacthub.io/signKey: |
        fingerprint: 6FCD850E18E4A4FF76DD1184A3A42A61961E423F
        url: https://yourls.org/.well-known/openpgpkey/hu/6e4gbtp15q1znf3unweeducn7urty4mr
    apiVersion: v2
    appVersion: 1.9.1
    created: "2026-05-05T19:05:08.406106-05:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: ^2.1.2
    - condition: mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      tags:
      - yourls-database
      version: ^11.3.4
    description: Your Own URL Shortener (forked while waiting for https://github.com/YOURLS/charts/pull/215)
    digest: 312c6288348402987cced54a50cab0c22ba03492930b8c6dce42614066710be9
    home: https://yourls.org
    icon: https://yourls.org/images/yourls-logo.svg
    keywords:
    - shortener
    - url
    - bitly
    kubeVersion: ^1.20.0-0
    maintainers:
    - name: YOURLS
      url: https://github.com/YOURLS
    - name: LeoColomb
      url: https://github.com/LeoColomb
    name: yourls
    sources:
    - https://github.com/YOURLS/YOURLS
    - https://github.com/YOURLS/charts
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/yourls-5.2.12.tgz
    version: 5.2.12
generated: "2026-05-05T19:05:08.396984-05:00"
