apiVersion: v1
entries:
  cronjob:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-05-21T01:16:46.847004-05:00"
    description: A Helm chart for deploying a CronJob.
    digest: baf011ba08dfca9247954dce1db964e79a82f399b208c37db2479257a6f17728
    name: cronjob
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/cronjob-v0.1.0.tgz
    version: v0.1.0
  httpd:
  - apiVersion: v2
    appVersion: 2.4.54
    created: "2026-05-21T01:16:46.847856-05:00"
    description: A Helm chart to deploy httpd in Kubernetes
    digest: f642b7d64beb8d724c3d2c644a03046d722c9f673e8b82e490f8c4eb4ad97b41
    name: httpd
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/httpd-v0.1.1.tgz
    version: v0.1.1
  keycloak:
  - apiVersion: v2
    appVersion: 26.0.0
    created: "2026-05-21T01:16:46.848328-05:00"
    description: Production-ready Keycloak Helm chart with external DB or embedded
      PostgreSQL
    digest: 1c9b76f1eb66a3b5a4007c61e662d927d8a004e1fc83b10e1f245e1da5bb7dca
    name: keycloak
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/keycloak-0.1.0.tgz
    version: 0.1.0
  yourls:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Add diggest parameters to prepare bitnami/common v2
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Upstream Project
          url: https://github.com/YOURLS/YOURLS
      artifacthub.io/signKey: |
        fingerprint: 6FCD850E18E4A4FF76DD1184A3A42A61961E423F
        url: https://yourls.org/.well-known/openpgpkey/hu/6e4gbtp15q1znf3unweeducn7urty4mr
    apiVersion: v2
    appVersion: 1.9.1
    created: "2026-05-21T01:16:46.855781-05:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: ^2.1.2
    - condition: mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      tags:
      - yourls-database
      version: ^11.3.4
    description: Your Own URL Shortener (forked while waiting for https://github.com/YOURLS/charts/pull/215)
    digest: 0643e48c83c784cd0f03c616361229b35a0359bfc969ca016f96025322bd7f4a
    home: https://yourls.org
    icon: https://yourls.org/images/yourls-logo.svg
    keywords:
    - shortener
    - url
    - bitly
    kubeVersion: ^1.20.0-0
    maintainers:
    - name: YOURLS
      url: https://github.com/YOURLS
    - name: LeoColomb
      url: https://github.com/LeoColomb
    name: yourls
    sources:
    - https://github.com/YOURLS/YOURLS
    - https://github.com/YOURLS/charts
    type: application
    urls:
    - https://helm-charts-two.vercel.app/charts/yourls-5.2.12.tgz
    version: 5.2.12
generated: "2026-05-21T01:16:46.846313-05:00"
