{{- if eq .Values.database.mode "embedded" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.embedded.database | quote }}
  POSTGRES_USER: {{ .Values.database.embedded.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.embedded.password | quote }}
{{- end }}
