{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.adminSecretName" . }}
type: Opaque
stringData:
  {{ .Values.admin.passwordKey }}: {{ .Values.admin.password | quote }}
{{- end }}
